#!/usr/bin/env bash
# a script that installs ngin my silent mode
sudo apt-get update -y
sudo apt-get -y install nginx

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
