#!/usr/bin/env bash
#For online documentation and support please refer to and futher info required
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
